package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/benrea/rover-example/graphql/gqlgen"
)

// Echo is the resolver for the echo field.
func (r *queryResolver) Echo(ctx context.Context, message *string) (string, error) {
	if message == nil {
		return "<nil>", nil
	}

	return *message, nil
}

// Query returns gqlgen.QueryResolver implementation.
func (r *Resolver) Query() gqlgen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
